apiVersion: v1
kind: Service
metadata:
  name: api-service # ← ESTE nombre es lo que usas desde otros pods
spec:
  type: NodePort
  selector:
    app: shpd-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081  # Puedes cambiar este puerto si está en uso



