apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  selector:
    app: shpd-backend
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
      nodePort: 30765  # <- Este puerto lo abrís externamente
