apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rodolgiaco/shpd:1.0
        ports:
        - containerPort: 8765
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"