apiVersion: apps/v1
kind: Deployment
metadata:
  name: shpd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shpd-backend
  template:
    metadata:
      labels:
        app: shpd-backend
    spec:
      containers:
      - name: backend
        image: rodolgiaco/shpd-backend:5.3
        ports:
        - containerPort: 8765
          hostPort: 8765
          protocol: TCP
        - containerPort: 8000 
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@postgres-service:5432/shpd_db
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"